### ISSUE TITLE
Unable to get credentials of 1 person

### ISSUE THREAD

**Issue by lolfoollor** [ntu-se7-grp3/garang-guni#43]
Credentials doesnt display only 1 person at a time but everyone in an array.

**Comment by asherchew** [comment]
1. User register for a new account
![image](https://github.com/user-attachments/assets/62b271a1-098e-4e33-9ac3-f5f0382e9cdc)

2. User gets redirect to Home Page thereafter.
![image](https://github.com/user-attachments/assets/436144ac-b6bf-4771-bfc0-ed263e179ec8)

Issue fixed in PR Fix Css #42
